name: CD Gitops

on:
  push:
    branches: [main]

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/gitops:latest,${{ secrets.DOCKER_USERNAME }}/gitops:${{ github.sha }}

    - name: Setup kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: '4.5.7'

    - name: Update kubernetes resources
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        cd k8s
        kustomize edit set image nodeserver=DOCKER_USERNAME/gitops:$GITHUB_SHA

    - name: Commit changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "action@github.com"
        git commit -m "Bump docker version"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        repository: fernandopascoalbr/gitops