name: CD Gitops

on:
  push:
    branches: [main]

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.GIT_REPOSITORY }}/gitops
        tags: ${{ github.sha }}, latest
